"""create files table

Revision ID: 00cb002b2fb0
Revises: d9397556e231
Create Date: 2026-04-11 19:42:12.732998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cb002b2fb0'
down_revision: Union[str, Sequence[str], None] = 'd9397556e231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_id_key'), 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sessions_id_key'), 'sessions', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
