"""

Revision ID: d9397556e231
Revises: 1e87e2573d57
Create Date: 2026-04-11 13:36:16.043810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9397556e231'
down_revision: Union[str, Sequence[str], None] = '1e87e2573d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('latest_message', sa.Text(), server_default=sa.text("''::text"), nullable=False))
    op.add_column('sessions', sa.Column('latest_message_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'sessions', ['id'])
    op.drop_column('sessions', 'last_message')
    op.drop_column('sessions', 'last_message_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('last_message', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'latest_message_at')
    op.drop_column('sessions', 'latest_message')
    # ### end Alembic commands ###
