services:
  mini_manus_sandbox_dev:
    # 容器服务构建来源
    build:
      context: ../
      dockerfile: .devops/Dockerfile
    # 将当前目录挂载到工作空间 /workspace
    volumes:
      - ../:/sandbox
    # 端口映射
    ports:
      - "2222:22" # 本地2222端口映射到容器22端口
      - "9528:9528" # 本地9528端口映射到容器9528端口
    # 容器服务名称
    container_name: mini_manus_sandbox_dev
    # 重启策略
    restart: always